import{i as p,S as m}from"./assets/vendor-8c59ed88.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const s of t.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&i(s)}).observe(document,{childList:!0,subtree:!0});function n(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function i(e){if(e.ep)return;e.ep=!0;const t=n(e);fetch(e.href,t)}})();function f(o){const r="https://pixabay.com/",n="api/",i=new URLSearchParams({key:"44428338-9196df2338f39a1a95b2ab25e",image_type:"photo",orientation:"horizontal",q:`${o}`,safesearch:!0}),e=`${r}${n}?${i}`;return fetch(e).then(t=>t.json()).then(t=>t.hits)}const a=document.querySelector(".img-list");function d(o){f(o).then(r=>{if(r&&r.length>0){const n=y(r);a.insertAdjacentHTML("beforeend",n),g()}else p.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"})}).catch(r=>r),a.innerHTML=""}function h({webformatURL:o,largeImageURL:r,tags:n,likes:i,views:e,comments:t,downloads:s}){return`<li><a href="${r}">
        <img src=${o} alt=${n} data-source=${r}/></a>
        <div>
            <p>likes: <span>${i}</span></p>
            <p>views: <span>${e}</span></p>
            <p>comments: <span>${t}</span></p>
            <p>downloads: <span>${s}</span></p>
        </div>
    </li>`}function y(o){return o.map(h).join("")}function g(){new m(".img-list a",{overlayOpacity:.9,captionDelay:250,captionsData:"alt"}).refresh()}const l=document.querySelector(".form-el"),c=l.querySelector(".input-search"),u=document.querySelector(".loader");l.addEventListener("submit",o=>{o.preventDefault(),u.classList.remove("visually-hidden"),setTimeout(v,2e3)});function v(){u.classList.add("visually-hidden"),c.value.trim()!==""&&d(c.value.trim())}
//# sourceMappingURL=commonHelpers.js.map
